### ISSUE TITLE
Share data model for use in other cities?

### ISSUE THREAD

**Issue by maxine** [jdalt/twin-cities-aid-distribution-locations#1]
Hi, thanks so much for making this tool. Can you share a template of the google spreadsheet you're using so that this can be used in other cities as well?

**Comment by maxine** [comment]
Created a [doc](https://docs.google.com/spreadsheets/d/1IIDsFN-If0IfNrRO-I3WbisHAz7EGjJ8aviSboX_-z4/edit?usp=sharing) based on the one I found for MN, so closing issue

**Comment by comeoneileen** [comment]
I'd like to weigh in on some of this before you disseminate it - there's a LOT of stuff going on behind the scenes in the not-public sheet that the public one scrapes form.

**Comment by maxine** [comment]
@comeoneileen got it! thanks for letting me know. I'll only work on updates to the Twin Cities map for now.

**Comment by comeoneileen** [comment]
Thanks! Could we connect via Zoom sometime this evening? (We're focusing on either resting or keeping the current map updated until curfew)

**Comment by maxine** [comment]
@comeoneileen yes! Feel free to reach out to me at mpwhitely@gmail.com. @andyinabox 's contact info is on [his site](http://andydayton.com/)
