### ISSUE TITLE
Feedback collection mechanism

### ISSUE THREAD

**Issue by samanpwbb** [jdalt/twin-cities-aid-distribution-locations#11]
In order to know how to make this resource more useful, we should add a feedback collection mechanism:

![Screen Shot 2020-06-01 at 1 24 37 PM](https://user-images.githubusercontent.com/108094/83451080-43f5d000-a40b-11ea-8a09-84b7aae66924.png)

In order to do this we need:

- [ ] Create google form – @mc-funk  is speaking with some of the organizers about how to make something like this happen, see conversation is opentwincities.slack.com's `#proj-aid-locations-map`.
- [ ] Implement button in app

**Comment by samanpwbb** [comment]
Looks like most of the feedback is being collected through facebook groups – this might not be necessary at all.

**Comment by mc-funk** [comment]
Good to keep track of this need for sure. 
Also, your diagram is so pretty

**Comment by jdalt** [comment]
I think we need to answer for the usability problem soliciting feedback on the map somehow. Right now there's a link back to the source google doc with no indication of how to push information to facebook. I'm not certain how the experience for the folks on the spread sheet is right now. I'll try and post back here with a point of view once I've got more information (still just waking up from a nap).

**Comment by samanpwbb** [comment]
> I think we need to answer for the usability problem soliciting feedback on the map somehow.

It would be possible to allow user to click a point on the map, click a "report" button, and then be taken to a google doc with lat/long and possibly other fields pre-filled (See https://stackoverflow.com/questions/27844608/google-surveys-a-way-to-pass-url-parameters-into-survey, https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/).

![Screen Shot 2020-06-01 at 5 30 34 PM](https://user-images.githubusercontent.com/108094/83467016-9fd15080-a42d-11ea-9b68-e4190325e630.png)

**Comment by jdalt** [comment]
That sounds really great and it could save the volunteers a bunch of time.

I think first, I'd like to just get the facebook process documented since I don't even fully understand it in all its glory. I think there might be new facebook group in the works to make this process easier (to sort of divide publishing and data input responsibilities).

@mc-funk would be you be able to document our current process and comment on a world in which google forms pipe data about. I'm especially interested in what's best for the people at the sites (are these the folks we're calling Penguins in the Zoom meetings?).

**Comment by jdalt** [comment]
I also want to say that I really love how google sheets + google forms + maps fit together in a hackathon/crowdsourcing environment. When the near term needs aren't quite as pressing I'd love to see how we could box this up for use in hackathonlike environments. There are going to be people in other cities would could use a box of stuff like this and couple of instructions for assembly.

**Comment by mc-funk** [comment]
Created #25 to get Twilio set up to allow runners to send a text that feeds a spreadsheet. No implementation direction as of yet, we'll need ideas on how to make this work well in terms of ease of use for both runners and data entry folks.

**Comment by jdalt** [comment]
Migrated to new repo
