### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by andyinabox** [jdalt/twin-cities-aid-distribution-locations#2]
Would be happy to help with this proj if there's anything needed.

**Comment by maxine** [comment]
+1

**Comment by andyinabox** [comment]
@jdalt I'm going to start adding issues for things I think could improve the map. Plz let me know if there's anything I can do to be more helpful, like managing PRs. Or if this just isn't really helpful at all :)

**Comment by andyinabox** [comment]
hi @maxine are you working on this too rn? lets keep in touch so we don't duplicate work. :smile_cat:. i'm gonna try and make issues and assign to myself if i'm working on them

**Comment by jdalt** [comment]
@andyinabox @maxine 
Do you two want to be direct contributors on the repo? I'm literally going to pass out very soon and if you can keep pushing out good changes I'm happy to hand things over while I get some sleep.

The important thing to keep in mind is that this is driven off of a google sheets document as a backend and you don't want to push anything that might break that -- for instance you'll probably want to coordinate color palette changes with the folks updating the sheet.

**Comment by jdalt** [comment]
I'd love to get some filtering in that side panel and tons of other usability improvements.

**Comment by jdalt** [comment]
I would also imagine that google sheet + map is probably something that would useful to folks in other places.

**Comment by comeoneileen** [comment]
Hi. Yes. I also helped get this going and also haven't slept since...sometime yesterday morning but I'm around for a while as well. Yes, we definitely need help. Thank you for being here!

**Comment by maxine** [comment]
@jdalt made a [template Google sheet](https://docs.google.com/spreadsheets/d/1IIDsFN-If0IfNrRO-I3WbisHAz7EGjJ8aviSboX_-z4/edit#gid=0) with examples. Lmk if you want me to add you as a contributor so you can update any formatting I missed / got incorrect. For using this template in other areas, I'll look into how many times one mapbox API key can be used/the best way to deploy this multiple times

**Comment by andyinabox** [comment]
@jdalt yes add me as a contrib! happy to manage this while you get some rest... THANK YOU (and @comeoneileen) for getting this going!!!

**Comment by jdalt** [comment]
@maxine @andyinabox You've been added as contributors. @comeoneileen is already one as well as my partner @estherrose046 and a couple other folks I've invited (trying to get a couple people from my place of work to keep an eye things too).

I've reached out to the mapbox folks to try and get a bump in map capacity, but I think we should be good for now.

**Comment by mc-funk** [comment]
@jdalt @maxine should I add the lat-long script to the spreadsheet example? 
Also I can link a gist with the scripts and the demo spreadsheet in the readme and submit a PR for that

**Comment by hinzed1127** [comment]
hey y'all, another Minneapolis web developer looking to help 👋  

I don't want to duplicate work, but let me know where I can jump in. could be helpful to have some kind of messaging channel, as info for a lot of these orgs and their various needs is changing so quickly.

**Comment by andyinabox** [comment]
> could be helpful to have some kind of messaging channel, as info for a lot of these orgs and their various needs is changing so quickly.

yes! i was just thinking that

**Comment by maxine** [comment]
@jdalt @comeoneileen is it ok with you if I set up a Slack channel for this? Or is there some other way you'd prefer to communicate?

**Comment by samanpwbb** [comment]
👋  I've been looking for ways to help out as well – am a generalist engineer/designer with a lot of experience with maps :) – if there's a slack channel going I'd love an invite.

**Comment by jdalt** [comment]
@maxine I'd welcome a slack channel. We might also be able to use one of the existing public groups like msptech.slack.com.

**Comment by mc-funk** [comment]
@jdalt maybe Open Twin Cities since it's in the civic hacking space?

**Comment by maxine** [comment]
@jdalt @mc-funk @samanpwbb @comeoneileen @hinzed1127 @andyinabox just made a slack channel called `#proj-aid-locations-map` in Open Twin Cities (just joined their Slack from [their website](http://www.opentwincities.org/))

**Comment by jasonthibeault** [comment]
Hey folks, @comeoneileen suggested I could help out, and I'm more than willing, internet connection allowing (I'm very rural right now). Going to join the Slack channel ASAP.

**Comment by experimatt** [comment]
Hi friends! I'm in to help, too!

**Comment by gabe-bergstrom** [comment]
I'm also here to help!

**Comment by jdalt** [comment]
Migrated to new repo
