### ISSUE TITLE
Filtering additions

### ISSUE THREAD

**Issue by maxine** [jdalt/twin-cities-aid-distribution-locations#21]
adding to functionality introduced in #19 :
- [ ] if a drop-off spot is open for both receiving and distributing donations, it should be shown as part of the filtered list when either of those two options are checked
- [x] Add "needs volunteers" filter
- [x] Add "needs money" filter

**Comment by maxine** [comment]
From @jdalt: the cards are getting somewhat busy and some od this is due to the diversity of information coming from donation sites. I wonder if we could use some text-overflow css to tame the variation.

**Comment by jdalt** [comment]
Migrated to new repo
