### ISSUE TITLE
Staging environment? 

### ISSUE THREAD

**Issue by mc-funk** [jdalt/twin-cities-aid-distribution-locations#24]
How much effort would it be to get a staging environment on this? 

Moreso than just thinking about being able to test, I'm wondering how we can easily show the results of PRs that change the UX to stakeholders to get feedback.  

It hasn't been super necessary yet but it's easy to imagine that being useful/needed.

**Comment by andyinabox** [comment]
Pretty sure Netlify will give this to us for free. Investigating...

**Comment by andyinabox** [comment]
@jdalt @mc-funk this should be pretty easy, but i'm blocked by not being the repo owner. Is this a good enough reason to move to a group repo?

**Comment by jdalt** [comment]
@andyinabox It's a good enough reason if the effort to get deploy and redirect is less than me getting Netlify up and running.

What are the steps to do this and is it even possible (seems not) to delegate this ability to you?

**Comment by andyinabox** [comment]
@jdalt I don't think it should be difficult to get netlify up and running tbh. they're pretty well integrated into github

**Comment by jdalt** [comment]
Migrated to new repo
