### ISSUE TITLE
Allow reporters to submit map updates through a text line (twilio)

### ISSUE THREAD

**Issue by mc-funk** [jdalt/twin-cities-aid-distribution-locations#25]
Does anyone have time this morning (Tuesday) to get Twilio set up so that we can distribute a phone number for “penguins”, aka runners in the field getting site info,  to text, and it would go into our google workbook so that volunteers could review and then update the data? 

See: https://www.twilio.com/blog/2018/05/receive-sms-messages-google-sheets-apps-script.html

This would mean people in the field could get us an update without having to find Facebook or a form link.

Since Twilio has been outspoken I suspect they might also be open to giving us some help e.g. discounts. 

If someone can work on this this morning, I can get you the access you need to the spreadsheet, but you'll want to be in the OTC slack. 

No implementation direction as of yet, we'll need ideas on how to make this work well in terms of ease of use for both runners and data entry folks.

**Comment by experimatt** [comment]
I'm in touch with Kevin Whinnery from Twilio and can coordinate getting help here

**Comment by experimatt** [comment]
I emailed Kevin about this a little bit ago and CCed Michelle

**Comment by jdalt** [comment]
Migrated to new repo
