### ISSUE TITLE
Map should include documentation about how to contribute to it

### ISSUE THREAD

**Issue by andyinabox** [jdalt/twin-cities-aid-distribution-locations#26]
Related to #25 

The map needs to tell people how to update it. There’s that little Data Source thing on the legend now but that’s not terribly helpful since it just directs folks to read only google sheet. Things are changing on the ground so there’s not a ton of clarity here but we need  work with the folks bridging the development and pavement level volunteer efforts to communicate the process.

**Comment by mc-funk** [comment]
I am hoping by midday today we will have (1) a google form and (2) a number to text.  We have someone working on the former and calls out for someone to work on the latter.

**Comment by jdalt** [comment]
Migrated to new repo
