### ISSUE TITLE
A domain name for forwarding? 

### ISSUE THREAD

**Issue by mc-funk** [jdalt/twin-cities-aid-distribution-locations#30]
This would make it easier to share with or without domain masking. 
Especially if we are going to migrate to a group, but also just to increase ease of sharing.

**Comment by jdalt** [comment]
Domain name ideas?

https://twin-cities-mutual-aid.org
https://tc-aid.org
https://tc-mutual-aid.org
...

Does anybody got the skills to do this and do it quick?

**Comment by jdalt** [comment]
We (by proxy of me) own https://twin-cities-mutual-aid.rog

**Comment by experimatt** [comment]
This is done!
