### ISSUE TITLE
Fully transfer code and deployment to mutual-aid org

### ISSUE THREAD

**Issue by samanpwbb** [jdalt/twin-cities-aid-distribution-locations#33]
We plan to use https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations as the source of truth for this project. Here's a proposed plan of action:

- [x] decide on new domain name. (https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/30)
- [x] purchase a new domain to publish to 
- [x] Deploy from https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations
- [x] Set up domain forwarding for both urls: jdalt.github.io/twin-cities-aid-dstribution-locations and https://Twin-Cities-Mutual-Aid.github.io/twin-cities-aid-distribution-locations/ – see https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain for instructions
- [x] Replace the code in https://github.com/jdalt/twin-cities-aid-distribution-locations with a note about the transfer, once we've set up domain forwarding.

We could alternatively _NOT_ use a custom domain and continue publshing using the github.io url, in which case the plan above would need to change a bit.

So, next actions are:
1. Pick a domain name
2. Register the name and set up forwarding (anyone available to own this part of the work?)

**Comment by experimatt** [comment]
I think purchasing the new domain and setting up the redirects from the old URL to the new one are separate tasks.

Also, I think there are some typos in the forwarding URLs in your original post. It should be: `https://jdalt.github.io/twin-cities-aid-distribution-locations/`

**Comment by jdalt** [comment]
I'd like to complicate this as little as possible and a domain name is somewhat important choice. Do we have to make choice now and if so can we make it fast?

**Comment by jdalt** [comment]
We own https://twin-cities-mutual-aid.org

**Comment by experimatt** [comment]
@jdalt I found this gist on how to redirect from a gh pages project to another URL, although I'm not 100% sure that it'll work for us: https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

Other stuff I found assumed we're using gatsby, which doesn't apply.

**Comment by benjifs** [comment]
I just tried this by forking the repo, publishing to my netlify, and setting up redirect from github pages. It seems to work pretty well from @experimatt 's links.

https://benjifs.github.io/twin-cities-aid-distribution-locations/

**Comment by jdalt** [comment]
Just need to change the fork status now.

**Comment by jdalt** [comment]
Migrated to new repo
