### ISSUE TITLE
Broken Meta Tag for Facebook Sharing 

### ISSUE THREAD

**Issue by mc-funk** [jdalt/twin-cities-aid-distribution-locations#34]
![image](https://user-images.githubusercontent.com/10001418/83553094-5d148480-a4d0-11ea-9dbd-a1df061b9405.png)
Facebook sharing is showing a broken image. Porbably related to a missing meta:og tag that fb uses to get image

**Comment by experimatt** [comment]
I can look into this

**Comment by experimatt** [comment]
This is done and merged!

**Comment by jdalt** [comment]
Fix in https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/35
Can someone verify this is fixed and close?

**Comment by experimatt** [comment]
Confirmed that the og:image preview shows in up slack on the new URL, so I presume it works in facebook too. Closing this

**Comment by experimatt** [comment]
Nevermind I don't have permissions to close this, but someone else can
