### ISSUE TITLE
Make main menu sortable/filterable

### ISSUE THREAD

**Issue by andyinabox** [jdalt/twin-cities-aid-distribution-locations#4]
- [ ] by loc status
 - [ ] whether loc has urgent needs
 - ~~neighborhood/region?~~
 - [ ] needs volunteers
 - [ ] needs $$$

**Comment by comeoneileen** [comment]
Into all of it except I'd say hold off on neighborhood/region - anyone who would want to sort by neighborhood name will get the same info by looking at it on the map, no?
