### ISSUE TITLE
Consolidated list of needs

### ISSUE THREAD

**Issue by andyinabox** [jdalt/twin-cities-aid-distribution-locations#5]
Data is might be too messy for this but would be pretty helpful.

**Comment by comeoneileen** [comment]
Agreed with pretty helpful, especially to make sure that people aren't missing requests for Tylenol because the person entering wrote Tylanol (...has happened today), but yes, so messy.

**Comment by jdalt** [comment]
I wonder if this is something to think about at the google sheets layer of things. It's sort of a "backend" and data modeling concern.

We could probably aggregate between sheets. I also wonder what sort of data sanitization tricks are available in sheets.

**Comment by andyinabox** [comment]
I agree, in the meantime I've been trying to think of ways to do this with what we've got. Here are my thoughts on how a rough implementation with the data we have would look like:

1. Create a map of synonyms or common misspellings (this could be done with google sheets) to help consolidate terms. Example in JSON format:

```json
{
  "advil" : "ibuprofin",
  "tylonol" : "tylenol"
}
```
2. Break up the "Accepting" and "Urgent Need" into individual tokens by splitting apart at commas
3. Create a map of weighted terms, adding to the weight each time a term is found. Items from "Accepting" are given a weight of 1, items from "Urgent Need" are given a weight of 1.5. Something like this:

```json
{
  "ibuprofin" : 6.5,
  "tylenol" : 5
}
```
4. Display only items that have a weight of 2+ (this will reduce noise, and also hopefully help filter out some messy data). A simple word cloud would probably work for this, with word size based on the weight.

I was also thinking this could actually just be a separate page that we could easily send to people hoping to donate, so they have a sense of what's needed...

**Comment by jdalt** [comment]
Migrated to new repo
