### ISSUE TITLE
More accessible color key

### ISSUE THREAD

**Issue by andyinabox** [jdalt/twin-cities-aid-distribution-locations#6]
Not super readable if you're color blind

**Comment by maxine** [comment]
Have a fix for this that doesn't require updates in the google sheet. will make a PR now👍

**Comment by comeoneileen** [comment]
I'm new to using Github for anything other than hosting pages. What's PR? And @maxine, what's your plan?

Also, @andyinabox, can you confirm that with someone who IS colorblind? We deliberately avoided red and green. I'm just not super familiar.

**Comment by maxine** [comment]
@comeoneileen thanks so much for your work on this so far! PR = pull request. You can review the palette I used/the changes I made in #7 . I'll hold off on merging unless at least one other person approves!

**Comment by andyinabox** [comment]
@comeoneileen 

> I'm new to using Github for anything other than hosting pages. What's PR?

A common workflow for GitHub is to Fork (copy) the codebase you want to contribute to, then make the edits in your own version. Then when you're done you submit a Pull Request (PR) so the owner can review the changes and merge into the original codebase. Apologies if I'm over-explaining, not sure what your experience level is.

> Also, @andyinabox, can you confirm that with someone who IS colorblind? We deliberately avoided red and green. I'm just not super familiar.

I'm R/G color blind and was having trouble reading the map. Not sure this is super urgent but figured it's pretty easy so I'd capture it.
